<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>j</string>
	</array>
	<key>name</key>
	<string>Obj-J</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#fwd_decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>accessor</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.decorator</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.option</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>entity.name.function.accessor</string>
			<key>match</key>
			<string>((@)accessors)(\(.*?(?:\b(readonly|copy))?\))?</string>
		</dict>
		<key>class</key>
		<dict>
			<key>begin</key>
			<string>(@)(implementation)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.js.objj</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.js.objj</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(@)(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.js.objj</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.js.objj</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.implementation.js.objj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code_block</string>
				</dict>
			</array>
		</dict>
		<key>class_decl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.js.objj</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.js.objj</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.js.objj</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.js.objj</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.js.objj</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z][a-zA-Z0-9_]+)\s*:\s*([a-zA-Z][a-zA-Z0-9_]+)\s*(?:(&lt;)((?:[a-zA-Z][a-zA-Z0-9_]+\s*,?\s*)+)(&gt;))?</string>
			<key>name</key>
			<string>meta.inheritance.objj</string>
		</dict>
		<key>code_block</key>
		<dict>
			<key>begin</key>
			<string>\s*{</string>
			<key>end</key>
			<string>\s*}</string>
			<key>name</key>
			<string>meta.code.block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#objj_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code_section</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code_block</string>
				</dict>
			</array>
		</dict>
		<key>code_section</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_objc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storage</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special_variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plain_argument</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#message</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
			</array>
		</dict>
		<key>comment_block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.js.objj</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.js.objj</string>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.js.objj</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.js.objj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.js.objj</string>
				</dict>
			</array>
		</dict>
		<key>fwd_decl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.forwarddeclaration.objj</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.js.objj</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@)(class)\s+([a-zA-Z][a-zA-Z0-9_]+)\s*;</string>
			<key>name</key>
			<string>meta.preprocessor.forwarddeclaration.objj</string>
		</dict>
		<key>import</key>
		<dict>
			<key>begin</key>
			<string>^\s*@(import)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.objj</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?://|/\*))|$</string>
			<key>name</key>
			<string>meta.preprocessor.objj.include</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.objj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.objj</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.include.objj</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.objj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.objj</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.lt-gt.include.objj</string>
				</dict>
			</array>
		</dict>
		<key>language_constants</key>
		<dict>
			<key>match</key>
			<string>\b(YES|NO|Nil|nil)\b</string>
			<key>name</key>
			<string>constant.language.js.objj</string>
		</dict>
		<key>message</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.objj</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.objj</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.bracketed</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=\w)(?&lt;=[\w\])"] )(\w+(?:(:)|(?=\])))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.any-method.js.objj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.arguments.js.objj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\])</string>
					<key>name</key>
					<string>meta.function-call.js.objj</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.arguments.js.objj</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b\w+(:)</string>
							<key>name</key>
							<string>support.function.any-method.name-of-parameter.js.objj</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#code_section</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#code_section</string>
				</dict>
			</array>
		</dict>
		<key>method_decl</key>
		<dict>
			<key>begin</key>
			<string>^\s*-|\+</string>
			<key>end</key>
			<string>(?=^\s*{)</string>
			<key>name</key>
			<string>meta.method.definition.objj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.begin.js.objj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.end.js.objj</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>@action</string>
							<key>name</key>
							<string>meta.return-type.special.js.objj</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b\w+\b</string>
							<key>name</key>
							<string>meta.return-type.js.objj</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\w+(?=:)</string>
					<key>name</key>
					<string>entity.name.function.name-of-parameter.js.objj</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.arguments.js.objj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.begin.js.objj</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))\s*(\w+\b)?</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.type.end.js.objj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.js.objj</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.argument.js.objj</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b\w+\b</string>
							<key>name</key>
							<string>meta.argument-type.js.objj</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment_block</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>objj_statement</key>
		<dict>
			<key>comment</key>
			<string>@outlet CSGProgram program @accessors;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.decorator.objj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.objj</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.objj</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(@outlet)?\s*\b(\w+)\b\s*\b(\w+)\b</string>
					<key>name</key>
					<string>meta.ivar.def.objj</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#accessor</string>
				</dict>
			</array>
		</dict>
		<key>plain_argument</key>
		<dict>
			<key>match</key>
			<string>\b\w+\b</string>
			<key>name</key>
			<string>meta.function-call.arguments</string>
		</dict>
		<key>special_variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b_cmd\b</string>
					<key>name</key>
					<string>variable.other.selector.js.objj</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(self|super)\b</string>
					<key>name</key>
					<string>variable.language.js.objj</string>
				</dict>
			</array>
		</dict>
		<key>storage</key>
		<dict>
			<key>begin</key>
			<string>(@)(class|selector|protocol)\b\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.storage.type.js.objj</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>name</key>
			<string>storage.type.js.objj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\w:]+</string>
					<key>name</key>
					<string>entity.name</string>
				</dict>
			</array>
		</dict>
		<key>string_objc</key>
		<dict>
			<key>begin</key>
			<string>@"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.js.objj</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.js.objj</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.js.objj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|[abefnrtv'"?]|[0-3]\d{,2}|[4-7]\d?|x[a-zA-Z0-9]+)</string>
					<key>name</key>
					<string>constant.character.escape.js.objj</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.js.objj</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.objj</string>
	<key>uuid</key>
	<string>22999C66-D6BD-4759-AFBB-4E504DD69146</string>
</dict>
</plist>
